eureka:
  client:
    service-url:
      DEFAULT_URL: http://localhost:8761/eureka/
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/ybing_auth?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: root
#  jpa:
#    database: mysql
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
  liquibase:
    change-log: classpath:/db/changelog/master.xml

mapper:
  not-empty: true
  mappers: com.ybing.authentication.common.YbingBaseMapper
  identity: mysql
mybatis:
  type-aliases-package: com.ybing.authentication.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
