spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ybing_blog?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password:
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  redis:
    host: localhost
eureka:
  client:
    service-url:
      DEFAULT_URL: http://localhost:8761/eureka/
mapper:
  identity: mysql
  mappers: com.ybing.blog.common.YbBaseMapper
  not-empty: true
mybatis:
  type-aliases-package: com.ybing.blog.entity


